# Generated by Django 4.1.2 on 2022-10-26 16:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('passphrase_hash', models.CharField(max_length=250)),
                ('salt', models.CharField(max_length=250)),
                ('active', models.BooleanField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(default=datetime.datetime(2022, 10, 26, 16, 0, 58, 720268, tzinfo=datetime.timezone.utc))),
                ('updated_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nces_id', models.PositiveBigIntegerField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(default=datetime.datetime(2022, 10, 26, 16, 0, 58, 693642, tzinfo=datetime.timezone.utc))),
                ('updated_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user_type', models.CharField(max_length=50)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.school')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField(default=datetime.datetime(2022, 10, 26, 16, 0, 58, 721045, tzinfo=datetime.timezone.utc))),
                ('updated_by', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='projects.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='projects.user')),
            ],
        ),
        migrations.CreateModel(
            name='ClassUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.class')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.user')),
            ],
        ),
    ]
